[project]
name = "awsome-ai-agents"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "e2b-code-interpreter>=2.9.0",
]

[project.optional-dependencies]
learner = [
    "jupyter",
    "ipykernel",
    "pydantic",
    "openai",
    "anthropic",
    "langchain",
    "langgraph",
    "langchain-openai",
    "pyautogen",
    "crewai",
    "agentops",
    "pandas",
    "mcp",
    "chromadb",
    "opentelemetry-api",
    "opentelemetry-sdk",
    "temporalio",
    "dspy-ai",
    "semantic-router==0.1.16",
    "matplotlib",
    "numpy",
    "tqdm",
    "umap-learn"
]
contributor = [
    "awsome-ai-agents[learner]",
    "pytest",
    "nbclient",
    "nbformat",
]

[tool.setuptools]
py-modules = []
packages = ["awsome_agents"]
