"use client";

import { useEffect, useMemo, useState } from "react";


import { guidePaths, curriculumData as subjects, Subject } from "./page-data";
type Level = "Beginner" | "Intermediate" | "Advanced" | "Enterprise Agent";
const base = "https://github.com/mahsa-teimourikia/awesome-ai-agents/blob/main/";

const levels:Record<Level,{sub:string;color:string}>={Beginner:{sub:"Build one trustworthy agent",color:"mint"},Intermediate:{sub:"Improve and measure tools",color:"gold"},Advanced:{sub:"Design for coordination",color:"coral"},"Enterprise Agent":{sub:"Scale to production",color:"blue"}};

export default function Home(){
 const [level,setLevel]=useState<"All"|Level>("All"); const [selected,setSelected]=useState(subjects[0]); const [tab,setTab]=useState<"learn"|"lab"|"quiz">("learn"); const [answers,setAnswers]=useState<Record<number,number>>({}); const [completed,setCompleted]=useState<string[]>([]);
 useEffect(()=>{try{const saved=window.localStorage.getItem("ai-agents-field-guide-progress-v1");if(saved)setCompleted(JSON.parse(saved));}catch{}} ,[]);
 useEffect(()=>{try{window.localStorage.setItem("ai-agents-field-guide-progress-v1",JSON.stringify(completed));}catch{}} ,[completed]);
 const filtered=useMemo(()=>level==="All"?subjects:subjects.filter(s=>s.level===level),[level]); 
 
 const isCorrect = (q:any, j:number) => Array.isArray(q.answer) ? q.answer.includes(j) : q.answer === j;
 const score=selected.quiz.reduce((n,q,i)=>n+(answers[i] !== undefined && isCorrect(q, answers[i]) ? 1 : 0),0);
 const select=(s:Subject)=>{setSelected(s);setTab("learn");setAnswers({});window.setTimeout(()=>document.getElementById("lesson-workspace")?.scrollIntoView({behavior:"smooth",block:"start"}),0);};
 
 return <main>
  <nav className="nav"><div className="brand"><span className="brand-mark">✦</span><span>AI AGENTS / <em>FIELD GUIDE</em></span></div><div className="nav-links"><a href="#curriculum">Curriculum</a><a href="/awesome-ai-agents/quiz/">Full quiz</a><a href="#how">How it works</a><a className="repo" href="https://github.com/mahsa-teimourikia/awesome-ai-agents" target="_blank">Open repo ↗</a></div></nav>
  <section className="hero"><div className="hero-copy"><div className="eyebrow">THE OPEN-SOURCE PATH · FROM THEORY TO OPERATIONS</div><h1>Build agents<br/><span>that know why.</span></h1><p className="hero-lede">A notebook-first learning hub built from the <em>awesome-ai-agents</em> repository: follow one scenario, learn the theory, run the Python, break the system, measure the fix, and keep the evidence.</p><div className="hero-actions"><a className="button primary" href="#curriculum">Start the curriculum <span>↓</span></a><a className="text-link" href="/awesome-ai-agents/quiz/">Take the full quiz ↗</a></div><div className="hero-meta"><span><b>36</b> scenario notebooks</span><span><b>36</b> repo lessons</span><span><b>1</b> learning hub</span></div></div><div className="hero-art"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="core"><span>AGENTS</span><small>autonomous systems</small></div><div className="node node-a">01<br/><b>PLAN</b></div><div className="node node-b">02<br/><b>ACT</b></div><div className="node node-c">03<br/><b>OBSERVE</b></div><div className="art-caption">Your agent is only<br/><strong>as good as its bounds.</strong></div></div></section>
  <section className="signal"><div><span className="signal-icon">↗</span><b>FOLLOW THE REPO</b><p>Objectives, notebooks, exercises, and next steps are mapped from the source material.</p></div><div><span className="signal-icon">⌁</span><b>LEARN IN LOOPS</b><p>Read a concept. Run the lab. Change one variable. Inspect the failure.</p></div><div><span className="signal-icon">◌</span><b>CHECK YOUR SIGNAL</b><p>Use the checkpoint quiz and the repo’s tests to see what actually stuck.</p></div></section>

  <section id="curriculum" className="curriculum"><div className="section-intro"><div><div className="eyebrow">THE CURRICULUM MAP</div><h2>One path.<br/>Four altitudes.</h2></div><p>The repo recommends starting with a beginner bounded loop, then improving tool engineering, and finally designing for teams, memory, and enterprise operations.</p></div><div className="progress-summary" aria-live="polite">{completed.length} of {subjects.length} lessons complete</div><div className="level-tabs"><button className={level==="All"?"active":""} onClick={()=>setLevel("All")}>All lessons <span>· {subjects.length} modules</span></button>{(["Beginner","Intermediate","Advanced","Enterprise Agent"] as Level[]).map(l=><button key={l} className={level===l?"active":""} onClick={()=>setLevel(l)}>{l}<span>· {levels[l].sub}</span></button>)}</div><div className="curriculum-grid">{filtered.map(s=><button className={"subject-card " + (selected.id===s.id?"selected ":"") + "level-" + s.level.replace(" ", "-")} key={s.id} onClick={()=>select(s)}><div className="card-top"><span className={"pill " + levels[s.level].color}>{s.level} · {s.step}</span><span className="duration">{s.time}</span>{completed.includes(s.id)&&<span className="completed-mark" aria-label="Completed">✓</span>}</div><h3>{s.title}</h3><p>{s.description}</p><span className="card-arrow">→</span></button>)}</div></section>
  <section id="lesson-workspace" className="workspace"><div className="workspace-heading"><div><div className="eyebrow">LESSON {selected.step} · {selected.level.toUpperCase()}</div><h2>{selected.title}</h2></div><div className="session-count"><span className="dot"/> {selected.time} <span>·</span> repo-grounded</div></div><div className="lesson-tabs"><button onClick={()=>setTab("learn")} className={tab==="learn"?"active":""}>01 / Learn</button><button onClick={()=>setTab("lab")} className={tab==="lab"?"active":""}>02 / Lab</button><button onClick={()=>setTab("quiz")} className={tab==="quiz"?"active":""}>03 / Checkpoint</button></div><div className="workspace-body">
   {tab==="learn"&&<><div className="lesson-copy"><div className="eyebrow">OUTCOME</div><p className="outcome">{selected.outcome}</p><button className="complete-lesson" onClick={()=>setCompleted(completed.includes(selected.id)?completed.filter(id=>id!==selected.id):[...completed,selected.id])}>{completed.includes(selected.id)?"Completed ✓":"Mark lesson complete"}</button><div className="material-actions"><a className="button primary" href={base+guidePaths[selected.id]} target="_blank">Read lesson material ↗</a><a className="notebook-link inline-link" href={base+selected.notebook} target="_blank">Open companion notebook ↗</a></div><div className="eyebrow">THE IDEA</div><p className="big-copy">{selected.lesson}</p><div className="failure-strip"><span className="eyebrow">WATCH FOR</span>{selected.failures.map(f=><span key={f}>× {f}</span>)}</div></div><div className="diagram"><div className="diagram-label">THE STUDY LOOP</div><div className="flow"><div className="flow-box">Read<small>concept</small></div><i>→</i><div className="flow-box active-box">Run<small>notebook</small></div><i>→</i><div className="flow-box">Change<small>one thing</small></div></div><div className="diagram-note">Make the failure visible.<br/><span>Then turn the fix into a test.</span></div><div className="reference-list"><span className="eyebrow">SOURCE MATERIAL</span>{selected.refs.map((r,i)=><a key={r} href={r.startsWith("http")?r:base+r} target="_blank"><span>0{i+1}</span>{r} ↗</a>)}</div><div className="next-step"><span className="eyebrow">AFTER THIS LESSON</span><p>{selected.level==="Beginner"?"Continue to the next beginner module, then move on to the intermediate track.":selected.level==="Intermediate"?"Continue to the next experiment, keeping a golden set open as you tune.":"Continue to the next advanced pattern, carrying forward authorization, evaluation, and traceability."}</p><button onClick={()=>{const n=subjects[subjects.findIndex(x=>x.id===selected.id)+1];if(n)select(n)}}>Next lesson →</button></div></div></>}
   {tab==="lab"&&<div className="lab-layout workspace-single-column"><div className="lesson-copy"><div className="eyebrow">PRACTICAL LAB</div><p className="big-copy">{selected.exercise}</p><a className="notebook-link" href={base+selected.notebook} target="_blank" style={{marginBottom: "20px", display: "inline-block"}}>Run the guided notebook ↗</a>{selected.goals&&selected.goals.length>0&&<div className="lab-goals-container" style={{marginTop:"20px"}}><div className="eyebrow" style={{marginBottom: "15px"}}>LAB GOALS</div><ul className="lab-goals" style={{lineHeight:"1.6", color:"var(--muted)", fontSize:"14px", paddingLeft:"20px", margin:0}}>{selected.goals.map((g:string)=><li key={g} style={{marginBottom:"10px"}}>{g}</li>)}</ul></div>}</div>{selected.code?<pre><code>{selected.code}</code></pre>:null}</div>}
   {tab==="quiz"&&<div className="quiz workspace-single-column"><div className="quiz-head"><div><div className="eyebrow">CHECKPOINT QUIZ</div><p>Answer from the lesson. The repo’s original quiz uses the same habit: explain why, then follow the source.</p></div><div className="score">{Object.keys(answers).length?score + "/" + selected.quiz.length:"—"}<small>score</small></div></div>{selected.quiz.map((q:any,i:number)=><div className="question" key={q.q}><b>{String(i+1).padStart(2,"0")} / {q.q}</b><div className="options">{q.options.map((o:string,j:number)=><button key={o} onClick={()=>setAnswers({...answers,[i]:j})} className={answers[i]===j?(isCorrect(q, j)?"correct":"wrong"):""}>{o}<span>{answers[i]===j?(isCorrect(q, j)?"✓":"×"):""}</span></button>)}</div>{answers[i]!==undefined&&q.explanation&&<details style={{marginTop:"15px",color:"var(--muted)",fontSize:"13px",cursor:"pointer"}}><summary style={{fontWeight:"bold",color:"#287763"}}>Show Explanation</summary><div style={{marginTop:"8px",lineHeight:"1.5"}}>{q.explanation}</div></details>}</div>)}</div>}
  </div></section>
  <section id="how" className="footer-cta"><div className="eyebrow">THE REPO’S RULE OF THUMB</div><h2>Read the idea.<br/><span>Run the evidence.</span></h2><p>Every lesson here links back to the original <a href="https://github.com/mahsa-teimourikia/awesome-ai-agents" target="_blank">awesome-ai-agents</a> curriculum, notebooks, and references. Use the full quiz when you want one cross-topic knowledge check.</p><a className="button dark" href="/awesome-ai-agents/quiz/">Open the full quiz ↗</a></section><footer><span>AI AGENTS / FIELD GUIDE</span><span>OPEN SOURCE · LEARN IN PUBLIC</span><a href="https://oneplusi.io" target="_blank">ONE+i · RESPONSIBLE AI ↗</a><a href="https://github.com/mahsa-teimourikia/awesome-ai-agents" target="_blank">github ↗</a></footer>
 </main>;
}
