import { lessons } from "./lessons.js";
const base = "https://github.com/mahsa-teimourikia/awsome-ai-agents/blob/main/";
const filters = document.querySelector("#filters"), cards = document.querySelector("#cards"), workspace = document.querySelector("#workspace");
let selected = lessons[0], level = "All", completed = JSON.parse(localStorage.getItem("ai-agents-hub-progress") || "[]");
const link = path => path.startsWith("http") ? path : base + path;
function renderFilters(){filters.innerHTML=["All","Beginner","Intermediate","Advanced"].map(x=>`<button class="${level===x?"active":""}" data-level="${x}">${x}</button>`).join("");filters.querySelectorAll("button").forEach(b=>b.onclick=()=>{level=b.dataset.level;renderFilters();renderCards();});}
function renderCards(){const shown=level==="All"?lessons:lessons.filter(x=>x.level===level);cards.innerHTML=`<p class="progress">${completed.length}/${lessons.length} lessons complete</p>`+shown.map(x=>`<button class="card ${x.id===selected.id?"selected":""}" data-id="${x.id}"><span class="pill">${x.level} · ${x.step}</span><h3>${x.title} ${completed.includes(x.id)?"✓":""}</h3><p>${x.summary}</p><span class="arrow">→</span></button>`).join("");cards.querySelectorAll(".card").forEach(c=>c.onclick=()=>{selected=lessons.find(x=>x.id===c.dataset.id);renderCards();renderWorkspace();workspace.scrollIntoView({behavior:"smooth",block:"start"});});}
function renderWorkspace(){const isComplete=completed.includes(selected.id);workspace.innerHTML=`<div class="workspace-head"><div><p class="eyebrow">LESSON ${selected.step} · ${selected.level.toUpperCase()}</p><h2>${selected.title}</h2></div><span class="pill">${selected.level}</span></div><div class="lesson-grid"><article><p class="eyebrow">OUTCOME</p><p class="outcome">${selected.outcome}</p><p class="eyebrow">LEARNING LOOP</p><div class="loop"><span>Read material</span><b>→</b><span>Run the design</span><b>→</b><span>Check assumptions</span></div><div class="actions"><a class="button" href="${link(selected.material)}" target="_blank">Read lesson ↗</a><a class="text-link" href="${link(selected.lab)}" target="_blank">Open practical guide ↗</a></div><button class="complete" id="complete">${isComplete?"Completed ✓":"Mark lesson complete"}</button></article><aside><p class="eyebrow">SOURCES</p>${selected.refs.map((r,i)=>`<a class="source" href="${link(r)}" target="_blank"><span>0${i+1}</span>${r} ↗</a>`).join("")}<div class="checkpoint"><p class="eyebrow">LESSON CHECKPOINT</p><p>Can you explain the boundary, failure mode, and test for this lesson?</p><a class="quiz-link" href="../quiz/index.html">Take the full graded knowledge check ↗</a></div></aside></div>`;document.querySelector("#complete").onclick=()=>{completed=isComplete?completed.filter(id=>id!==selected.id):[...completed,selected.id];localStorage.setItem("ai-agents-hub-progress",JSON.stringify(completed));renderCards();renderWorkspace();};}
renderFilters();renderCards();renderWorkspace();
