import { lessons, checks } from "./lessons.js";
const base = "https://github.com/mahsa-teimourikia/awsome-ai-agents/blob/main/";
const filters = document.querySelector("#filters"), cards = document.querySelector("#cards"), workspace = document.querySelector("#workspace");
let selected = lessons[0], level = "All", tab = "learn", completed = JSON.parse(localStorage.getItem("ai-agents-hub-progress") || "[]");
const link = path => path.startsWith("http") ? path : base + path;
function renderFilters(){filters.innerHTML=["All","Beginner","Intermediate","Advanced"].map(x=>`<button class="${level===x?"active":""}" data-level="${x}">${x}</button>`).join("");filters.querySelectorAll("button").forEach(b=>b.onclick=()=>{level=b.dataset.level;renderFilters();renderCards();});}
function renderCards(){const shown=level==="All"?lessons:lessons.filter(x=>x.level===level);cards.innerHTML=`<p class="progress">${completed.length}/${lessons.length} lessons complete</p>`+shown.map(x=>`<button class="card ${x.id===selected.id?"selected":""}" data-id="${x.id}"><span class="pill">${x.level} · ${x.step}</span><h3>${x.title} ${completed.includes(x.id)?"✓":""}</h3><p>${x.summary}</p><span class="arrow">→</span></button>`).join("");cards.querySelectorAll(".card").forEach(c=>c.onclick=()=>{selected=lessons.find(x=>x.id===c.dataset.id);renderCards();renderWorkspace();workspace.scrollIntoView({behavior:"smooth",block:"start"});});}
function renderWorkspace(){const isComplete=completed.includes(selected.id), check=checks[selected.id], notebookLink=selected.notebook?`<a class="button" href="${link(selected.notebook)}" target="_blank">Open notebook ↗</a>`:"";const content=tab==="learn"?`<article><p class="eyebrow">OUTCOME</p><p class="outcome">${selected.outcome}</p><p class="eyebrow">THE IDEA</p><p>${selected.detail || "Read the linked material first, then explain the system boundary, control loop, and trade-offs in your own words."}</p><a class="button" href="${link(selected.material)}" target="_blank">Read lesson material ↗</a></article>`:tab==="lab"?`<article><p class="eyebrow">PRACTICAL LAB</p><p class="outcome">${selected.run || "Run the design, change one assumption, and inspect the failure mode."}</p><p>Use the Python module or notebook, record the inputs and outputs, and keep policy checks outside the model.</p><a class="button" href="${link(selected.lab)}" target="_blank">Open practical guide ↗</a>${notebookLink}</article>`:`<article><p class="eyebrow">CHECKPOINT</p><ol><li><b>${check[0]}</b></li><li>What failure mode would you test for?</li><li>What evidence would convince you the design works?</li></ol><details><summary>Reveal an answer guide</summary><p>${check[1]}</p></details><a class="quiz-link" href="../quiz/index.html">Take the full graded Knowledge Check ↗</a></article>`;workspace.innerHTML=`<div class="workspace-head"><div><p class="eyebrow">LESSON ${selected.step} · ${selected.level.toUpperCase()}</p><h2>${selected.title}</h2></div><span class="pill">${selected.level}</span></div><div class="lesson-tabs"><button class="${tab==="learn"?"active":""}" data-tab="learn">01 / Learn</button><button class="${tab==="lab"?"active":""}" data-tab="lab">02 / Lab</button><button class="${tab==="checkpoint"?"active":""}" data-tab="checkpoint">03 / Checkpoint</button></div><div class="lesson-grid">${content}<aside><p class="eyebrow">SOURCES</p>${selected.refs.map((r,i)=>`<a class="source" href="${link(r)}" target="_blank"><span>0${i+1}</span>${r} ↗</a>`).join("")}<button class="complete" id="complete">${isComplete?"Completed ✓":"Mark lesson complete"}</button></aside></div>`;workspace.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{tab=b.dataset.tab;renderWorkspace();});document.querySelector("#complete").onclick=()=>{completed=isComplete?completed.filter(id=>id!==selected.id):[...completed,selected.id];localStorage.setItem("ai-agents-hub-progress",JSON.stringify(completed));renderCards();renderWorkspace();};}
renderFilters();renderCards();renderWorkspace();
