export const lessons = [
  {id:"b1",level:"Beginner",step:"01",title:"Agent foundations",summary:"Define agents, workflows, tools, state, and safe stop conditions.",material:"docs/what-is-an-ai-agent.md",lab:"labs/beginner/01_agent_loop.py",outcome:"Explain what makes a system an agent and identify its control boundary.",refs:["docs/what-is-an-ai-agent.md#a-practical-definition","https://openai.com/business/guides-and-resources/a-practical-guide-to-building-ai-agents/"]},
  {id:"b2",level:"Beginner",step:"02",title:"The agent loop",summary:"Trace observe → decide → act → observe and make every transition inspectable.",material:"docs/what-is-an-ai-agent.md#the-agent-loop",lab:"labs/beginner/03_checkpointed_state.py",outcome:"Design a bounded loop with typed actions, observations, budgets, and terminal states.",refs:["docs/what-is-an-ai-agent.md#the-agent-loop","https://arxiv.org/abs/2210.03629"]},
  {id:"b3",level:"Beginner",step:"03",title:"Tools and memory",summary:"Create narrow tool contracts and separate working state from long-term memory.",material:"docs/what-is-an-ai-agent.md#tools",lab:"labs/beginner/02_tool_contracts.py",outcome:"Specify a typed, authorized tool and a safe memory-write policy.",refs:["docs/what-is-an-ai-agent.md#tools","docs/what-is-an-ai-agent.md#state-and-memory"]},
  {id:"i1",level:"Intermediate",step:"01",title:"Workflows versus agents",summary:"Choose the least autonomous design that reliably solves the task.",material:"docs/agentic-workflows.md",lab:"labs/intermediate/02_langgraph_workflow.py",outcome:"Compare deterministic workflows, agentic workflows, and open-ended agents using explicit trade-offs.",refs:["docs/agentic-workflows.md#workflow-versus-agent","https://www.anthropic.com/engineering/building-effective-agents"]},
  {id:"i2",level:"Intermediate",step:"02",title:"Architecture patterns",summary:"Apply routing, parallelization, orchestrator-worker, and evaluator-optimizer patterns.",material:"docs/architecture-patterns.md",lab:"docs/multi-agent-systems.md",outcome:"Select a topology, define contracts, and identify its failure modes before implementation.",refs:["docs/architecture-patterns.md","docs/multi-agent-systems.md"]},
  {id:"i3",level:"Intermediate",step:"03",title:"Evaluation and security",summary:"Evaluate trajectories, tool calls, outcomes, policy compliance, and cost.",material:"docs/evaluation-and-security.md",lab:"docs/evaluation-and-security.md#release-gates",outcome:"Create a release gate that catches unsafe actions and unsuccessful task trajectories.",refs:["docs/evaluation-and-security.md#evaluation-dimensions","https://www.anthropic.com/engineering/demystifying-evals-for-ai-agents"]},
  {id:"a1",level:"Advanced",step:"01",title:"Multi-agent teams",summary:"Design manager, handoff, peer, parallel, and graph topologies with explicit ownership.",material:"docs/multi-agent-systems.md",lab:"assets/multi-agent-patterns.mmd",outcome:"Explain when coordination overhead is justified and how to bound delegation.",refs:["docs/multi-agent-systems.md","assets/multi-agent-patterns.mmd"]},
  {id:"a2",level:"Advanced",step:"02",title:"Production operations",summary:"Add durable state, approvals, observability, replay, and rollback to long-running runs.",material:"docs/evaluation-and-security.md",lab:"docs/agentic-workflows.md#reliability-patterns",outcome:"Define operational SLOs and recovery paths for an agentic system.",refs:["docs/evaluation-and-security.md#release-gates","https://langchain-ai.github.io/langgraph/concepts/durable_execution/"]},
  {id:"a3",level:"Advanced",step:"03",title:"Interoperability and autonomy",summary:"Combine MCP, A2A, human boundaries, and autonomy measurement without losing control.",material:"README.md#tools-memory-and-protocols",lab:"README.md#multi-agent-systems",outcome:"Map protocol boundaries and choose where identity, policy, and approval are enforced.",refs:["https://modelcontextprotocol.io/","https://a2a-protocol.org/"]}
];
