export const lessons = [
  {id:"b1",level:"Beginner",step:"01",title:"Agent foundations",summary:"Define agents, workflows, tools, state, and safe stop conditions.",material:"docs/what-is-an-ai-agent.md",lab:"labs/beginner/01_agent_loop.py",outcome:"Explain what makes a system an agent and identify its control boundary.",refs:["docs/what-is-an-ai-agent.md#a-practical-definition","https://openai.com/business/guides-and-resources/a-practical-guide-to-building-ai-agents/"]},
  {id:"b2",level:"Beginner",step:"02",title:"The agent loop",summary:"Trace observe → decide → act → observe and make every transition inspectable.",material:"docs/what-is-an-ai-agent.md#the-agent-loop",lab:"labs/beginner/03_checkpointed_state.py",outcome:"Design a bounded loop with typed actions, observations, budgets, and terminal states.",refs:["docs/what-is-an-ai-agent.md#the-agent-loop","https://arxiv.org/abs/2210.03629"]},
  {id:"b3",level:"Beginner",step:"03",title:"Tools and memory",summary:"Create narrow tool contracts and separate working state from long-term memory.",material:"docs/what-is-an-ai-agent.md#tools",lab:"labs/beginner/02_tool_contracts.py",outcome:"Specify a typed, authorized tool and a safe memory-write policy.",refs:["docs/what-is-an-ai-agent.md#tools","docs/what-is-an-ai-agent.md#state-and-memory"]},
  {id:"i1",level:"Intermediate",step:"01",title:"Workflows versus agents",summary:"Choose the least autonomous design that reliably solves the task.",material:"docs/agentic-workflows.md",lab:"labs/intermediate/02_langgraph_workflow.py",outcome:"Compare deterministic workflows, agentic workflows, and open-ended agents using explicit trade-offs.",refs:["docs/agentic-workflows.md#workflow-versus-agent","https://www.anthropic.com/engineering/building-effective-agents"]},
  {id:"i2",level:"Intermediate",step:"02",title:"Architecture patterns",summary:"Apply routing, parallelization, orchestrator-worker, and evaluator-optimizer patterns.",material:"docs/architecture-patterns.md",lab:"labs/intermediate/01_architecture_patterns.py",outcome:"Select a topology, define contracts, and identify its failure modes before implementation.",refs:["docs/architecture-patterns.md","docs/multi-agent-systems.md"]},
  {id:"i3",level:"Intermediate",step:"03",title:"Evaluation and security",summary:"Evaluate trajectories, tool calls, outcomes, policy compliance, and cost.",material:"docs/evaluation-and-security.md",lab:"labs/intermediate/03_evaluation_release_gate.py",outcome:"Create a release gate that catches unsafe actions and unsuccessful task trajectories.",refs:["docs/evaluation-and-security.md#evaluation-dimensions","https://www.anthropic.com/engineering/demystifying-evals-for-ai-agents"]},
  {id:"a1",level:"Advanced",step:"01",title:"Multi-agent teams",summary:"Design manager, handoff, peer, parallel, and graph topologies with explicit ownership.",material:"docs/multi-agent-systems.md",lab:"labs/advanced/01_multi_agent_team.py",outcome:"Explain when coordination overhead is justified and how to bound delegation.",refs:["docs/multi-agent-systems.md","assets/multi-agent-patterns.mmd"]},
  {id:"a2",level:"Advanced",step:"02",title:"Production operations",summary:"Add durable state, approvals, observability, replay, and rollback to long-running runs.",material:"docs/evaluation-and-security.md",lab:"labs/advanced/02_durable_recovery.py",outcome:"Define operational SLOs and recovery paths for an agentic system.",refs:["docs/evaluation-and-security.md#release-gates","https://langchain-ai.github.io/langgraph/concepts/durable_execution/"]},
  {id:"a3",level:"Advanced",step:"03",title:"Interoperability and autonomy",summary:"Combine MCP, A2A, human boundaries, and autonomy measurement without losing control.",material:"README.md#tools-memory-and-protocols",lab:"labs/advanced/03_protocol_boundaries.py",outcome:"Map protocol boundaries and choose where identity, policy, and approval are enforced.",refs:["https://modelcontextprotocol.io/","https://a2a-protocol.org/"]},
  {id:"a4",level:"Advanced",step:"04",title:"Safety readiness",summary:"Threat-model prompt injection, tool abuse, memory poisoning, and budget exhaustion.",material:"docs/evaluation-and-security.md#threat-model",lab:"labs/advanced/04_safety_readiness.py",outcome:"Turn threat-model findings into a production readiness gate and rollback plan.",refs:["docs/evaluation-and-security.md","https://genai.owasp.org/"]},
  {id:"a5",level:"Advanced",step:"05",title:"Research team capstone",summary:"Coordinate search, critique, synthesis, citations, evaluation, and escalation.",material:"docs/multi-agent-systems.md",lab:"labs/advanced/05_multi_agent_research_capstone.py",outcome:"Compare a bounded multi-agent team with a simpler single-agent baseline.",refs:["docs/multi-agent-systems.md","labs/notebooks/05_multi_agent_research.ipynb"]}
];

export const checks = {
  b1: ["Which boundary keeps tools safe?", "Application policy and authorization outside the model."],
  b2: ["What should stop a loop?", "A success condition, budget, policy block, or safe terminal state."],
  b3: ["What should a tool contract include?", "Typed inputs, authorization, risk metadata, and useful errors."],
  i1: ["When should you prefer a workflow?", "When the path is predictable and control or auditability matters."],
  i2: ["What should you compare before adding agents?", "Success, cost, latency, coordination overhead, and failure modes."],
  i3: ["What belongs in an agent release gate?", "Outcome, policy, trajectory, cost, and regression checks."],
  a1: ["What makes a multi-agent team safe?", "Explicit roles, contracts, ownership, budgets, and termination rules."],
  a2: ["Why use idempotency?", "To make retries and replay safe around side effects."],
  a3: ["Where should interoperability authorization live?", "At the application protocol boundary, not in model instructions alone."]
  ,a4: ["What makes a system production-ready?", "Passing threat-model, authorization, budget, rollback, and evaluation checks."]
  ,a5: ["What should a research team preserve?", "Role ownership, source IDs, bounded delegation, evaluation, and escalation."]
};
